print("어린이에게 들려줄 짧은 이야기를 만들어 주세요.")
background = ("이야기의 배경: ")
mainCharactor = input("주인공 이름: ")
noun1 = input("명사1: ")
noun2 = input("명사2: ")
adjective1 = input("꾸미는 말1: ")
adjective2 = input("꾸미는 말2: ")
adjective3 = input("꾸미는 말3: ")
noun2Name = input("명사2의 이름:")
adjective4 = input("꾸미는 말4: ")
emotion1 = input("감정: ")
emotion2 = input("감정2: ")


print()
print(mainCharactor, "는 ", noun1, "를 타고 밤하늘을 여행하고 있어요.")
print(mainCharactor, "의 눈에 ", noun2, "이 보여요!")
print("'", adjective1, "'", mainCharactor, "는 손을 뻗어", noun2, "을 만져봅니다.")
print("'", adjective2, "'", noun2, "에서 예쁜 소리가 났어요!")
print(mainCharactor, "는 그 소리가 너무 아름답게 느껴졌어요.")
print('그 순간,', noun2, "이", mainCharactor, '에게 말을 걸어옵니다. "안녕?"')
print(mainCharactor, "가", noun2, "에게 말했어요.")
print(mainCharactor, '는', noun2,'에게 대답해요. "안녕? 말을 할 수 있구나!', adjective3, '소리를 내는 너의 이름은 뭐니?"')
print(noun2, "는 말했어요.", "내 이름은", noun2Name ,"이야. 네 이름은 뭐니?")
print("내 이름은", mainCharactor, "야. 반가워." , noun2Name, "아, 나와 친구가 되지 않을래?")
print("'", adjective4,"'",  noun2Name, '이 빛을 내며 웃는 얼굴로 대답해요. "좋아!"')
print(mainCharactor, "가", emotion1,"한 기분을 느끼네요.")
print(noun2Name, "도", emotion1, "한 모양이에요.")
print(noun2Name, "이", mainCharactor, "에게 무슨 말을 하고 있네요! 무슨 말인지 들어볼까요?")
print(mainCharactor, "야, 너와 친구가 되서", emotion2, '.')

print("당신이 만든 이야기, 마음에 드나요? ^^")