print("안녕하세요! 다음 질문에 답하고 이야기를 완성하세요.")
print() # 빈 줄 출력
animal = input("떠오르는 동물 입력: ")
name = input("떠오르는 이름 입력: ")
adjective1 = input ("떠오르는 형용사1 입력: ")
color1 = input("떠오르는 색깔 입력: ")
adjective2 = input("떠오르는 형용사2 입력: ")
food1 = input("떠오르는 음식1 입력: ")
food2 = input("떠오르는 음식2 입력: ")
food3 = input("떠오르른 음식3 입력: ")
adjective3 = input("떠오르는 형용사3 입력: ")
color2 = input("떠오르는 색깔2 입력: ")
noun4 = input("떠오르는 명사4 입력: ")

print("다음은 당신이 만든 이야기입니다.")
print()
print("저의 반려동물은", animal, "이고 이름은", name, "입니다.")
print(adjective1, "(이)고", color1, "색이며, ", adjective2, "니다.")
print(name, "은(는)", food1, food2, food3, "을(를) 먹습니다.")
print("가장 좋아하는 장난감은", adjective3, color2, noun4, "입니다.")